### ISSUE TITLE
evaluateJavascript xojo android

### ISSUE THREAD

**Issue by tsapap** [XojoGermany/AndroidDesignExtensions#1]
With your library I was able to apply the useragent to my MobileHTMLViewer.
I haven't figured out how to use your library to inject javascript code like xojo desktop's evaluatejavascript function

**Comment by XojoGermany** [comment]
> I haven't figured out how to use your library to inject javascript code like xojo desktop's evaluatejavascript function

I have tried to include this in the development process itself, but to no avail, as declares cannot use delegates in Xojo. Xojo's Android Declare engine is not currently ready for this. I am in exchange about this with the development team (private ticket). Xojo wrote about this:

> ... ExecuteJavascript itself might make it to the framework before a direct callback like this happens with declares.

**Comment by tsapap** [comment]
so there is no solution?

**Comment by XojoGermany** [comment]
> so there is no solution?

As far as I can tell at the moment, and based on feedback from the Xojo engineers, unfortunately no.

**Comment by XojoGermany** [comment]
Closing this case.

The next Xojo version 2023r3 will provide the MobileHTMLViewer extensions you need. If you are in the tester group, you can already test this.

Donations will be gladly accepted. 😉
