### ISSUE TITLE
Crashes with latest testversion 60805

### ISSUE THREAD

**Issue by portalzine** [XojoGermany/AndroidDesignExtensions#2]
The project currently crashes with the latest testversion.
Might be related to the latest HTMLViewer changes. Have not looked into it any deeper yet.
But thanks for the extensions ...
Cheers
Alexander

**Comment by XojoGermany** [comment]
### Workaround until the next Xojo 2023r3 Beta

1. Use the latest Commit  (https://github.com/XojoGermany/AndroidDesignExtensions/commit/112a253)
2. Add the `CancelLoad`-Event to **HTMLScreen.HTMLViewer1**

Donations will be gladly accepted. 😉

**Comment by portalzine** [comment]
Yeah that is what I got from Paul as well, for my last error report ;)
