### ISSUE TITLE
problem with the MobileHTMLViewer

### ISSUE THREAD

**Issue by tsapap** [XojoGermany/AndroidDesignExtensions#3]
I'm using your AndroidDesignExtensions, but I'm encountering a problem with the MobileHTMLViewer. I have assigned this UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36" to create automations on my WhatsApp Web. Unfortunately, when the app loads the URL https://web.whatsapp.com, the loading bar remains and the WhatsApp QR code for logging in is never shown. Is there a solution to this problem?

**Comment by XojoGermany** [comment]
This works:

```vb
Me.SetDomStorageEnabledXC(True)
Me.SetJavaScriptEnabledXC(True)
Me.SetUserAgentStringXC("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36")

Me.LoadURL("https://web.whatsapp.com/")
```

![Screenshot_1707239386](https://github.com/XojoGermany/AndroidDesignExtensions/assets/1276539/de2dda6a-8fb7-49f0-8af3-3220f8d2aaad)

**Comment by tsapap** [comment]
Thank you for your feedback.
