### ISSUE TITLE
ExecuteJavaScript

### ISSUE THREAD

**Issue by tsapap** [XojoGermany/AndroidDesignExtensions#5]
A JavaScript executed via ExecuteJavaScript can executeInXojo() to return data to the HTMLViewer via this event. Why doesn't it work on the htmlvier of your Android project?

To receive the parameters from the javascript in JavaScriptRequest do I have to enable any function?

Xojo 2024r1.1

I also followed these directions

Not realizing that the JavaScriptRequest event is not executed within the UI thread.
Not realizing that xojo.execute is the proper way to talk to the bridge via JS instead of executeInXojo.

**Comment by XojoGermany** [comment]
From your information it is not clear what problem you are having with regards to the Android Design Extensions? They refer to standard MobileHTMLViewer events.

Reading your lines, I don't think your issue has anything to do with the Android Design Extensions.

Do you have an example project? Have you tried the Xojo Forum before?

Without detailed information, it is difficult to help at this point.

From the docs (https://documentation.xojo.com/api/user_interface/mobile/mobilehtmlviewer.html#mobilehtmlviewer-javascriptrequest):

> Called on **Android** only when [ExecuteJavaScript](https://documentation.xojo.com/api/user_interface/mobile/mobilehtmlviewer.html#mobilehtmlviewer-executejavascript) has been called and has been passed a JavaScript that calls `xojo.execute()`.

**Comment by tsapap** [comment]
Thank you for your response. I'll give you an example that should return the QR code's base64 in the console log, but unfortunately on Android it seems that the JavaScript request event doesn't receive any information from the JavaScript.

[Test Android JavaScriptRequest.xojo_binary_project.zip](https://github.com/XojoGermany/AndroidDesignExtensions/files/15065015/Test.Android.JavaScriptRequest.xojo_binary_project.zip)

**Comment by XojoGermany** [comment]
So, your JavaScript code in the "getQR" constant must be faulty. I have modified the project and you can see that the `JavaScriptRequest` event for "pageTitle" is firing.

[Test Android JavaScriptRequest.xojo_binary_project.zip](https://github.com/XojoGermany/AndroidDesignExtensions/files/15066860/Test.Android.JavaScriptRequest.xojo_binary_project.zip)

**Comment by tsapap** [comment]
You are right, my JavaScript was incorrect. I apologize for bothering you due to my carelessness.

**Comment by XojoGermany** [comment]
Glad to read you got it working. Can you share your solution please?
